### ISSUE TITLE
老哥可不可以写个readme

### ISSUE THREAD

**Issue by cbigeyes** [yuanxiaosc/Schema-based-Knowledge-Extraction#1]
能不能写个运行的readme，代码太多了看不过来

**Comment by yuanxiaosc** [comment]
> 能不能写个运行的readme，代码太多了看不过来

https://github.com/yuanxiaosc/Entity-Relation-Extraction 目前推荐你看这个管道式解决方案。最近还在着急写论文和找工作，本资源优化会滞后一些。
