### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wanglaiqi** [yuanxiaosc/Schema-based-Knowledge-Extraction#2]
/bin/spo_striples_generation_data_manage.py", line 142, in model_token_label_2_entity_sort_tuple_list
entity_part_list.append(token_in_not_UNK_list[idx])
IndexError: list index out of range

**Comment by wanglaiqi** [comment]
预测出来的predicate_token_label_list  好长  而且O很少，用的时候要根据 token_in_not_UNK_list的长度进行截断吗

**Comment by yuanxiaosc** [comment]
> 预测出来的predicate_token_label_list 好长 而且O很少，用的时候要根据 token_in_not_UNK_list的长度进行截断吗

是按照输入长度来截断即可，这份代码生成最终spo_list的代码还有很多要修改的，未来我在比赛结束后会更新，现在你可以先用 https://github.com/yuanxiaosc/Entity-Relation-Extraction 这个方法，目前效果更好
