### ISSUE TITLE
模型架构

### ISSUE THREAD

**Issue by ZTurboX** [yuanxiaosc/Schema-based-Knowledge-Extraction#3]
请问模型架构是怎么样的

**Comment by yuanxiaosc** [comment]
> 请问模型架构是怎么样的

模型是基于BERT(多层transform堆叠成的前馈神经网络)的联合模型，同时抽取语句中的实体和可能的关系。下一步可以通过其它模型或者规则把输出的关系和实体对应起来，这里采用了规则的办法，代码写在bin中。
